### ISSUE TITLE
cram to bam use samtools but not cramtools?

### ISSUE THREAD

**Issue by worker000000** [igsr/1000Genomes_data_indexes#3]
hi,all, 
there is only cram, but not bam in your exome_alignment directory, so you advice use samtools, because in websitehttps://github.com/enasequence/cramtools said  "CRAMTools is no longer supported. Please use Samtools"

so do you tool do you advice, thanks a lot

**Comment by susanfairley** [comment]
IGSR provides support via an email based helpdesk at info@1000genomes.org. If you would like support suing these resources, please contact the project there.

Kind regards.
